### ISSUE TITLE
Add the ability to automatically create Config rules

### ISSUE THREAD

**Issue by robbytaylor** [scalefactory/s3audit-ts#4]
Following on from https://github.com/scalefactory/s3audit/issues/3

Add support for creating the config rules, and maybe some form of alerting?

This would be disabled by default but could be enabled with a flag:

`s3audit --enable-config-rules`

**Comment by sftim** [comment]
We're archiving this repository. Please consider using https://github.com/scalefactory/s3audit-rs instead.
